id: 6dc39833-9dd7-4176-8523-952309374dbe
version: 6
vcShouldKeepItemLegacyProdMachine: false
name: SOCaaS - Sync with portal
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 1d972ef2-8170-4501-8724-bb47833f7dc0
    type: start
    task:
      id: 1d972ef2-8170-4501-8724-bb47833f7dc0
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: e88bac21-d4f8-4e1b-8f9b-bdb23df01522
    type: regular
    task:
      id: e88bac21-d4f8-4e1b-8f9b-bdb23df01522
      version: -1
      name: mssportal-create-alert
      description: Create an alert using Portal's MDR API
      script: MSS Portal - MDR|||mssportal-create-alert
      type: regular
      iscommand: true
      brand: MSS Portal - MDR
    scriptarguments:
      alert_id:
        simple: ${incident.alertid}
      created_at:
        complex:
          root: incident
          accessor: sourcecreatetime
          transformers:
          - operator: DateStringToISOFormat
            args:
              add_utc_timezone:
                value:
                  simple: "true"
              dayfirst: {}
              fuzzy: {}
              yearfirst: {}
      customer_id:
        simple: "33096"
      modified_at:
        complex:
          root: incident
          accessor: sourcecreatetime
          transformers:
          - operator: DateStringToISOFormat
            args:
              add_utc_timezone:
                value:
                  simple: "true"
              dayfirst: {}
              fuzzy: {}
              yearfirst: {}
      name:
        simple: ${incident.alertname}
      provider_id:
        simple: XSOAR_LOGRHYTHM
      raw_data:
        simple: '{}'
      severity:
        simple: MEDIUM
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 230
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 275,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
